name: SonarCloud Code Analysis
on:
  push:
    branches:
      - '**'


jobs:
  sonarcloud-analysis:
    name: Code Scanning
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run unit test with jacoco report
        run: ./gradlew test jacocoTestReport

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info


